#!/usr/bin/env bash
set -euo pipefail

repo_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
catalog=$repo_dir/tools/catalog.tsv
config_root=${XDG_CONFIG_HOME:-"$HOME/.config"}/scriptorium
data_root=${XDG_DATA_HOME:-"$HOME/.local/share"}/scriptorium
cache_root=${XDG_CACHE_HOME:-"$HOME/.cache"}/scriptorium
state_root=${XDG_STATE_HOME:-"$HOME/.local/state"}/scriptorium
selected_file=$config_root/tools.selected
state_file=$config_root/tools.state
mise_config=$config_root/mise.toml
env_file=$config_root/tools-env.sh
capabilities_file=$config_root/capabilities.md
reviewed_catalog_file=$config_root/tools.catalog-reviewed
pending_catalog_file=$state_root/tools-reconfigure-required
mise_bin=$data_root/runtime/mise
mise_version=2026.8.6
mise_x64_sha=96f6f1f416d868b78addd22746eefc7f4bf7820c6a3afa392a9f653f708c1644
mise_arm64_sha=f9bd051912beb8861bf248289bfb2d8c281ff00fcdf1e44d730b8ea7e859e9a4

mkdir -p -- "$config_root" "$data_root/runtime" "$cache_root" "$state_root"

catalog_rows() { awk -F '\t' '!/^#/ && NF >= 7' "$catalog"; }
catalog_names() { catalog_rows | cut -f1 | sort -u; }
selected() { grep -Fqx -- "$1" "$selected_file" 2>/dev/null; }

record_catalog_review() {
    local reviewed_tmp
    reviewed_tmp=$(mktemp "$config_root/.tools-catalog-reviewed.XXXXXX")
    catalog_names >"$reviewed_tmp"
    mv -- "$reviewed_tmp" "$reviewed_catalog_file"
    rm -f -- "$pending_catalog_file"
    chmod 600 -- "$reviewed_catalog_file"
}

reconcile_catalog() {
    local current_tmp previous_tmp new_tmp pending_tmp
    current_tmp=$(mktemp "$config_root/.tools-catalog-current.XXXXXX")
    previous_tmp=$(mktemp "$config_root/.tools-catalog-previous.XXXXXX")
    new_tmp=$(mktemp "$config_root/.tools-catalog-new.XXXXXX")
    catalog_names >"$current_tmp"
    if [[ -s $reviewed_catalog_file ]]; then
        sort -u -- "$reviewed_catalog_file" >"$previous_tmp"
        comm -13 "$previous_tmp" "$current_tmp" >"$new_tmp"
    elif [[ -s $selected_file ]]; then
        awk -F '\t' '!/^#/ && NF >= 7 && $4 == 1 {print $1}' "$catalog" | sort -u \
            | comm -23 - <(sort -u -- "$selected_file") >"$new_tmp"
    fi
    rm -f -- "$current_tmp" "$previous_tmp"
    if [[ -s $new_tmp ]]; then
        pending_tmp=$(mktemp "$state_root/.tools-reconfigure.XXXXXX")
        {
            cat -- "$pending_catalog_file" 2>/dev/null || true
            cat -- "$new_tmp"
        } | sed '/^$/d' | sort -u >"$pending_tmp"
        mv -- "$pending_tmp" "$pending_catalog_file"
    fi
    rm -f -- "$new_tmp"
}

bootstrap_mise() {
    local arch asset sha url temp downloader
    [[ -x $mise_bin ]] && return
    case $(uname -m) in
        x86_64|amd64) arch=x64; sha=$mise_x64_sha ;;
        aarch64|arm64) arch=arm64; sha=$mise_arm64_sha ;;
        *) printf 'Local tool installation is unsupported on architecture %s.\n' "$(uname -m)" >&2; return 1 ;;
    esac
    asset=mise-v${mise_version}-linux-${arch}
    url=https://github.com/jdx/mise/releases/download/v${mise_version}/${asset}
    temp=$(mktemp "$cache_root/.mise.XXXXXX")
    trap 'rm -f -- "$temp"' RETURN
    printf 'Downloading verified mise %s...\n' "$mise_version"
    if command -v curl >/dev/null 2>&1; then
        curl -fL --retry 2 --connect-timeout 10 -o "$temp" "$url"
    elif command -v wget >/dev/null 2>&1; then
        wget -q -O "$temp" "$url"
    else
        printf 'curl or wget is required for local tool installation.\n' >&2
        return 1
    fi
    printf '%s  %s\n' "$sha" "$temp" | sha256sum -c - >/dev/null
    install -m 700 -- "$temp" "$mise_bin"
    rm -f -- "$temp"
    trap - RETURN
}

mise_env() {
    export MISE_DATA_DIR=$data_root/mise
    export MISE_CACHE_DIR=$cache_root/mise
    export MISE_STATE_DIR=$state_root/mise
    export MISE_GLOBAL_CONFIG_FILE=$mise_config
    export MISE_IGNORED_CONFIG_PATHS="$HOME/.config/mise/config.toml:$HOME/.tool-versions"
}

command_version() {
    local command_name=$1 output
    output=$($command_name --version 2>/dev/null | head -n 1 || true)
    [[ -n $output ]] || output=available
    printf '%s\n' "$output" | tr '\t\n' '  '
}

system_command_path() {
    local command_name=$1 command_path
    command_path=$(command -v "$command_name" 2>/dev/null || true)
    [[ -n $command_path && $command_path != "$data_root/mise/shims/"* ]] || return 1
    printf '%s\n' "$command_path"
}

write_runtime_files() {
    local name command_name mise_id default tier label description provider version local_installed=0
    local state_tmp config_tmp env_tmp capabilities_tmp
    state_tmp=$(mktemp "$config_root/.tools-state.XXXXXX")
    config_tmp=$(mktemp "$config_root/.mise-config.XXXXXX")
    env_tmp=$(mktemp "$config_root/.tools-env.XXXXXX")
    capabilities_tmp=$(mktemp "$config_root/.capabilities.XXXXXX")
    printf '[tools]\n' >"$config_tmp"
    printf '%s\n' '# Generated by Scriptorium. Do not source outside scodex.' >"$env_tmp"
    printf 'export SCRIPTORIUM_ACTIVE=1\n' >>"$env_tmp"
    printf 'export SCRIPTORIUM_TOOLS=' >>"$env_tmp"
    printf '%s\n' '""' >>"$env_tmp"
    printf '%s\n' '### Available Scriptorium tools' >"$capabilities_tmp"

    while IFS=$'\t' read -r name command_name mise_id default tier label description; do
        selected "$name" || continue
        if system_command_path "$command_name" >/dev/null; then
            provider=system
            version=$(command_version "$command_name")
        elif [[ $mise_id == - ]]; then
            printf 'Skipping %s: it must already be installed.\n' "$name" >&2
            continue
        else
            bootstrap_mise || continue
            mise_env
            version=$($mise_bin latest "$mise_id" 2>/dev/null || true)
            [[ -n $version ]] || { printf 'Could not resolve %s.\n' "$name" >&2; continue; }
            if "$mise_bin" install "$mise_id@$version"; then
                printf '%s = "%s"\n' "$mise_id" "$version" >>"$config_tmp"
                provider=local
                local_installed=1
            else
                printf 'Could not install %s; continuing without it.\n' "$name" >&2
                continue
            fi
        fi
        printf '%s\t%s\t%s\t%s\n' "$name" "$provider" "$version" "$command_name" >>"$state_tmp"
        printf -- '- `%s` (`%s`): %s, %s — %s\n' "$name" "$command_name" "$provider" "$version" "$description" \
            >>"$capabilities_tmp"
    done < <(catalog_rows)

    mv -- "$config_tmp" "$mise_config"
    if (( local_installed )); then
        mise_env
        "$mise_bin" reshim
        printf 'export MISE_DATA_DIR=%q\n' "$data_root/mise" >>"$env_tmp"
        printf 'export MISE_CACHE_DIR=%q\n' "$cache_root/mise" >>"$env_tmp"
        printf 'export MISE_STATE_DIR=%q\n' "$state_root/mise" >>"$env_tmp"
        printf 'export MISE_GLOBAL_CONFIG_FILE=%q\n' "$mise_config" >>"$env_tmp"
        printf 'export MISE_IGNORED_CONFIG_PATHS=%q\n' \
            "$HOME/.config/mise/config.toml:$HOME/.tool-versions" >>"$env_tmp"
        printf 'export PATH=%q:"$PATH"\n' "$data_root/mise/shims" >>"$env_tmp"
    fi
    tools_csv=$(cut -f1 "$state_tmp" | paste -sd, -)
    printf 'export SCRIPTORIUM_TOOLS=%q\n' "$tools_csv" >>"$env_tmp"
    mv -- "$state_tmp" "$state_file"
    mv -- "$env_tmp" "$env_file"
    mv -- "$capabilities_tmp" "$capabilities_file"
    chmod 600 -- "$selected_file" "$state_file" "$mise_config" "$env_file" "$capabilities_file"
}

configure_text() {
    local explicit=${1:-} name command_name mise_id default tier label description answer chosen_tmp
    chosen_tmp=$(mktemp "$config_root/.tools-selected.XXXXXX")
    if [[ -n $explicit ]]; then
        tr ',' '\n' <<<"$explicit" | sed '/^$/d' >"$chosen_tmp"
    else
        while IFS=$'\t' read -r name command_name mise_id default tier label description; do
            if [[ $tier == available-only ]] && ! command -v "$command_name" >/dev/null 2>&1; then
                printf '%-12s unavailable (not installed): %s\n' "$label" "$description"
                continue
            fi
            if selected "$name"; then default=1; fi
            if [[ $default == 1 ]]; then
                read -r -p "Enable $label — $description? [Y/n] " answer
                [[ ${answer,,} == n || ${answer,,} == no ]] || printf '%s\n' "$name" >>"$chosen_tmp"
            else
                read -r -p "Enable $label — $description? [y/N] " answer
                [[ ${answer,,} == y || ${answer,,} == yes ]] && printf '%s\n' "$name" >>"$chosen_tmp"
            fi
        done < <(catalog_rows)
    fi
    sort -u -- "$chosen_tmp" >"$selected_file"
    rm -f -- "$chosen_tmp"
    write_runtime_files
    record_catalog_review
}

configure_tui() {
    local review=${1:-0} new_names=${2:-}
    local -a names labels descriptions commands defaults tiers marks enabled new_flags
    local name command_name mise_id default tier label description index=0 key count line is_new
    while IFS=$'\t' read -r name command_name mise_id default tier label description; do
        names+=("$name"); commands+=("$command_name"); defaults+=("$default"); tiers+=("$tier")
        labels+=("$label"); descriptions+=("$description")
        is_new=0
        [[ ,$new_names, == *,$name,* ]] && is_new=1
        new_flags+=("$is_new")
        if [[ $tier == available-only ]] && ! command -v "$command_name" >/dev/null 2>&1; then
            marks+=(0); enabled+=(0)
        elif selected "$name" || [[ $review != 1 && $default == 1 ]]; then
            marks+=(1); enabled+=(1)
        else
            marks+=(0); enabled+=(1)
        fi
    done < <(catalog_rows)
    count=${#names[@]}
    printf '\033[?25l'
    trap 'printf "\033[?25h"' RETURN
    while true; do
        if [[ $review == 1 ]]; then
            printf '\033[H\033[2JReview tools after update (arrows, space, Enter).\n'
            printf 'New tools: %s\nOnly your current selection is preselected.\n\n' "$new_names"
        else
            printf '\033[H\033[2JSelect tools (arrows, space, Enter):\n\n'
        fi
        for ((line=0; line<count; line++)); do
            [[ $line == $index ]] && printf '> ' || printf '  '
            label=${labels[line]}
            [[ ${new_flags[line]} == 1 ]] && label="$label (new)"
            if [[ ${enabled[line]} == 0 ]]; then
                printf '[-] %-12s not installed — %s\n' "$label" "${descriptions[line]}"
            elif [[ ${marks[line]} == 1 ]]; then
                printf '[x] %s — %s\n' "$label" "${descriptions[line]}"
            else
                printf '[ ] %s — %s\n' "$label" "${descriptions[line]}"
            fi
        done
        IFS= read -rsn1 key
        if [[ $key == $'\e' ]]; then
            read -rsn2 key
            [[ $key == '[A' ]] && index=$(((index-1+count)%count))
            [[ $key == '[B' ]] && index=$(((index+1)%count))
        elif [[ $key == ' ' && ${enabled[index]} == 1 ]]; then
            marks[index]=$((1-marks[index]))
        elif [[ -z $key ]]; then
            break
        fi
    done
    printf '\033[?25h\033[H\033[2J'
    trap - RETURN
    : >"$selected_file"
    for ((line=0; line<count; line++)); do
        [[ ${marks[line]} == 1 ]] && printf '%s\n' "${names[line]}" >>"$selected_file"
    done
    write_runtime_files
    record_catalog_review
}

status_tools() {
    if [[ ! -s $state_file ]]; then printf 'No optional tools are active.\n'; return; fi
    printf '%-14s %-9s %-12s %s\n' TOOL PROVIDER COMMAND VERSION
    while IFS=$'\t' read -r name provider version command_name; do
        printf '%-14s %-9s %-12s %s\n' "$name" "$provider" "$command_name" "$version"
    done <"$state_file"
}

check_updates() {
    local stamp=$state_root/tools-update-check now last output
    now=$(date +%s); last=$(cat "$stamp" 2>/dev/null || printf 0)
    (( now - last >= 604800 )) || return
    printf '%s\n' "$now" >"$stamp"
    [[ -x $mise_bin && -s $mise_config ]] || return
    mise_env
    output=$(timeout 10s "$mise_bin" outdated 2>/dev/null || true)
    [[ -z $output ]] || printf 'scriptorium: local tool updates are available; run scodex tools update\n'
}

update_tools() {
    [[ -x $mise_bin ]] || { printf 'No locally managed tools.\n'; return; }
    mise_env
    "$mise_bin" upgrade --bump
    write_runtime_files
}

remove_tools() {
    local names=${1:-} name provider version command_name mise_id selected_tmp filtered_tmp
    [[ -n $names ]] || { printf 'Usage: scodex tools remove NAME[,NAME...]\n' >&2; return 2; }
    selected_tmp=$(mktemp "$config_root/.tools-selected.XXXXXX")
    cp -- "$selected_file" "$selected_tmp" 2>/dev/null || : >"$selected_tmp"
    while IFS= read -r name; do
        if [[ -x $mise_bin ]]; then
            provider=$(awk -F '\t' -v name="$name" '$1 == name {print $2}' "$state_file" 2>/dev/null)
            version=$(awk -F '\t' -v name="$name" '$1 == name {print $3}' "$state_file" 2>/dev/null)
            mise_id=$(awk -F '\t' -v name="$name" '$1 == name {print $3}' "$catalog")
            if [[ $provider == local && -n $version && -n $mise_id ]]; then
                mise_env
                "$mise_bin" uninstall "$mise_id@$version" || true
            fi
        fi
        filtered_tmp=$(mktemp "$config_root/.tools-filtered.XXXXXX")
        awk -v name="$name" '$0 != name' "$selected_tmp" >"$filtered_tmp"
        mv -- "$filtered_tmp" "$selected_tmp"
    done < <(tr ',' '\n' <<<"$names")
    mv -- "$selected_tmp" "$selected_file"
    write_runtime_files
}

action=${1:-status}; shift || true
case $action in
    configure)
        if [[ ${1:-} == --select ]]; then configure_text "${2:-}"
        elif [[ ${1:-} == --review && -t 0 && -t 1 ]]; then configure_tui 1 "${2:-}"
        elif [[ -t 0 && -t 1 ]]; then configure_tui
        else printf 'Non-interactive configuration requires --select NAME[,NAME...].\n' >&2; exit 2
        fi
        ;;
    clear)
        : >"$selected_file"
        write_runtime_files
        record_catalog_review
        ;;
    reconcile) reconcile_catalog ;;
    apply) write_runtime_files ;;
    status) status_tools ;;
    check) check_updates ;;
    update) update_tools ;;
    remove) remove_tools "${1:-}" ;;
    env) [[ -f $env_file ]] && cat -- "$env_file" ;;
    *) printf 'Unknown tools action: %s\n' "$action" >&2; exit 2 ;;
esac
